-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 23:12:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema phonebills
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phonebills
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phonebills` DEFAULT CHARACTER SET utf8mb3 ;
USE `phonebills` ;

-- -----------------------------------------------------
-- Table `phonebills`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebills`.`users` (
  `username` VARCHAR(16) CHARACTER SET 'latin1' NOT NULL,
  `salt` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `password` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `position` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `usercounter` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`usercounter`, `username`),
  INDEX `fk_1_idx` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `phonebills`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebills`.`admins` (
  `username` VARCHAR(16) CHARACTER SET 'latin1' NOT NULL,
  `name` VARCHAR(32) CHARACTER SET 'latin1' NOT NULL,
  `surname` VARCHAR(32) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `create_time` TIMESTAMP(2) NULL DEFAULT CURRENT_TIMESTAMP(2),
  PRIMARY KEY (`username`),
  CONSTRAINT `FK_USERNAME`
    FOREIGN KEY (`username`)
    REFERENCES `phonebills`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `phonebills`.`bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebills`.`bills` (
  `idBILLS` BIGINT NOT NULL,
  `BILLSMonth` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `TELEPHONE_NUMBERS_idTELEPHONE_NUMBERS` BIGINT NOT NULL,
  `TELEPHONE_NUMBERS_PROGRAMME_idPROGRAMME` BIGINT NOT NULL,
  `extraCost` FLOAT NULL DEFAULT NULL,
  `totalCost` FLOAT NULL DEFAULT NULL,
  `BILLSPayment` VARCHAR(3) NOT NULL DEFAULT 'OXI',
  PRIMARY KEY (`idBILLS`, `TELEPHONE_NUMBERS_idTELEPHONE_NUMBERS`, `TELEPHONE_NUMBERS_PROGRAMME_idPROGRAMME`),
  INDEX `fk_BILLS_TELEPHONE_NUMBERS1_idx` (`TELEPHONE_NUMBERS_idTELEPHONE_NUMBERS` ASC, `TELEPHONE_NUMBERS_PROGRAMME_idPROGRAMME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `phonebills`.`sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebills`.`sellers` (
  `username` VARCHAR(16) CHARACTER SET 'latin1' NOT NULL,
  `name` VARCHAR(32) CHARACTER SET 'latin1' NOT NULL,
  `surname` VARCHAR(32) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `create_time` TIMESTAMP(2) NULL DEFAULT CURRENT_TIMESTAMP(2),
  `ADMINS_username` VARCHAR(16) CHARACTER SET 'latin1' NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_SELLERS_ADMINS1_idx` (`ADMINS_username` ASC) VISIBLE,
  INDEX `FK__USERNAME_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `FK__USERNAME`
    FOREIGN KEY (`username`)
    REFERENCES `phonebills`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SELLERS_ADMINS1`
    FOREIGN KEY (`ADMINS_username`)
    REFERENCES `phonebills`.`admins` (`username`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `phonebills`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebills`.`customers` (
  `username` VARCHAR(16) CHARACTER SET 'latin1' NOT NULL,
  `name` VARCHAR(32) CHARACTER SET 'latin1' NOT NULL,
  `surname` VARCHAR(32) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `create_time` TIMESTAMP(2) NULL DEFAULT CURRENT_TIMESTAMP(2),
  `CUSTOMERSTaxNumber` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `SELLERS_username` VARCHAR(16) CHARACTER SET 'latin1' NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `wallet` DECIMAL(10,2) NULL DEFAULT '0.00',
  INDEX `fk_CUSTOMERS_SELLERS_idx` (`SELLERS_username` ASC) VISIBLE,
  INDEX `FK_USER_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_CUSTOMERS_SELLERS`
    FOREIGN KEY (`SELLERS_username`)
    REFERENCES `phonebills`.`sellers` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USER`
    FOREIGN KEY (`username`)
    REFERENCES `phonebills`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `phonebills`.`programme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebills`.`programme` (
  `idPROGRAMME` BIGINT NOT NULL,
  `PROGRAMMEDescription` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `PROGRAMMESpeechTime` INT NULL DEFAULT NULL,
  `PROGRAMMESMSNumber` INT NULL DEFAULT NULL,
  `PROGRAMMEData` INT NULL DEFAULT NULL,
  `PROGRAMMECost` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idPROGRAMME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `phonebills`.`telephone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebills`.`telephone_numbers` (
  `idTELEPHONE_NUMBERS` VARCHAR(11) NOT NULL,
  `PROGRAMME_idPROGRAMME` BIGINT NOT NULL,
  `customers_username` VARCHAR(16) CHARACTER SET 'latin1' NOT NULL,
  `customers_SELLERS_username` VARCHAR(16) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`idTELEPHONE_NUMBERS`, `PROGRAMME_idPROGRAMME`, `customers_username`, `customers_SELLERS_username`),
  INDEX `fk_TELEPHONE_NUMBERS_PROGRAMME1_idx` (`PROGRAMME_idPROGRAMME` ASC) VISIBLE,
  INDEX `fk_telephone_numbers_customers1_idx` (`customers_username` ASC, `customers_SELLERS_username` ASC) VISIBLE,
  INDEX `fk_Cust_Seller_Username_idx` (`customers_SELLERS_username` ASC) VISIBLE,
  CONSTRAINT `fk_Cust_Seller_Username`
    FOREIGN KEY (`customers_SELLERS_username`)
    REFERENCES `phonebills`.`sellers` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Customer_Username`
    FOREIGN KEY (`customers_username`)
    REFERENCES `phonebills`.`customers` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PROGRAMMEID`
    FOREIGN KEY (`PROGRAMME_idPROGRAMME`)
    REFERENCES `phonebills`.`programme` (`idPROGRAMME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `phonebills`.`calls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebills`.`calls` (
  `idCALLS` VARCHAR(20) NOT NULL,
  `CALLSDuration` INT NULL DEFAULT NULL,
  `CALLSTimestamp` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `number` VARCHAR(11) NULL DEFAULT NULL,
  `IDprogramme` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`idCALLS`),
  INDEX `FK_PROGRAMME_idx` (`IDprogramme` ASC) VISIBLE,
  INDEX `FK_NUMBER_idx` (`number` ASC) VISIBLE,
  INDEX `fk_CALLS_BILLS1_idx` (`number` ASC, `IDprogramme` ASC) VISIBLE,
  CONSTRAINT `FK_NUMBER`
    FOREIGN KEY (`number`)
    REFERENCES `phonebills`.`telephone_numbers` (`idTELEPHONE_NUMBERS`),
  CONSTRAINT `FK_PROGRAMME`
    FOREIGN KEY (`IDprogramme`)
    REFERENCES `phonebills`.`programme` (`idPROGRAMME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `phonebills`.`numbers_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebills`.`numbers_state` (
  `number` VARCHAR(16) NOT NULL,
  `used` INT NULL DEFAULT NULL,
  PRIMARY KEY (`number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'NULL-->NOT USED\\\\\\\\n1-->USED\\\\\\\\n';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
